"""
Role 3: Big Data Analytics & BI Engineer
Batch ingestion pipeline: Parquet -> ClickHouse.

Consumes:
    data/fake_forecast_5m.parquet        (generated by generate_fake_data.py)
    data/fake_attribution_5m.parquet     (generated by generate_fake_data.py)
    output/forecast.parquet              (real ST-GNN output, when Role 1 is done)

Writes to:
    cartaq.forecast_log
    cartaq.attribution_log

Metrics tracked:
    - Ingestion throughput (rows / second)
    - Total elapsed time per table

Usage:
    cd Cartaq
    python src/analytics/ingest_to_clickhouse.py [--table forecast|attribution|all]

Requires:
    pip install clickhouse-driver pyarrow pandas
"""

import argparse
import json
import os
import time
from collections.abc import Iterator
from typing import Any

import pandas as pd
from clickhouse_driver import Client

# ── Config (override with env vars) ──────────────────────────────────────────
CH_HOST     = os.getenv("CLICKHOUSE_HOST",    "localhost")
CH_PORT     = int(os.getenv("CLICKHOUSE_PORT", "9000"))
CH_DATABASE = os.getenv("CLICKHOUSE_DB",      "cartaq")
CH_USER     = os.getenv("CLICKHOUSE_USER",    "cartaq_user")
CH_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD","cartaq_pass")
CHUNK_SIZE  = 200_000   # rows per INSERT batch - tuned for ClickHouse block size
# ─────────────────────────────────────────────────────────────────────────────

INGEST_PLAN = [
    {
        "name":    "forecast_log",
        "table":   "cartaq.forecast_log",
        "sources": [
            "data/fake_forecast_5m.parquet",   # fake data (Role 3 zero-blocker)
            "output/forecast.parquet",          # real ST-GNN output (Role 1 - swap when ready)
        ],
    },
    {
        "name":    "attribution_log",
        "table":   "cartaq.attribution_log",
        "sources": [
            "data/fake_attribution_5m.parquet",
        ],
    },
]


def get_client() -> Client:
    return Client(
        host=CH_HOST,
        port=CH_PORT,
        database=CH_DATABASE,
        user=CH_USER,
        password=CH_PASSWORD,
        settings={"use_client_time_zone": True},
    )


def chunk_df(df: pd.DataFrame, size: int) -> Iterator[pd.DataFrame]:
    for start in range(0, len(df), size):
        yield df.iloc[start : start + size]


def ingest_file(client: Client, path: str, table: str) -> dict[str, Any]:
    """Load a parquet file and INSERT in batches. Returns metrics dict."""
    print(f"  Reading {path}...")
    df = pd.read_parquet(path)
    total = len(df)
    print(f"  {total:,} rows -> {table}")

    rows_done = 0
    t0 = time.perf_counter()

    for i, chunk in enumerate(chunk_df(df, CHUNK_SIZE)):
        client.insert_dataframe(f"INSERT INTO {table} VALUES", chunk)
        rows_done += len(chunk)
        elapsed = time.perf_counter() - t0
        throughput = rows_done / elapsed
        pct = rows_done / total * 100
        print(
            f"    [{pct:5.1f}%] {rows_done:,}/{total:,} rows  "
            f"{throughput:,.0f} rows/s",
            end="\r",
        )

    total_elapsed = time.perf_counter() - t0
    final_tp = total / total_elapsed
    print(f"\n  OK - Ingested {total:,} rows in {total_elapsed:.1f}s  ({final_tp:,.0f} rows/s)")

    return {
        "table":                    table,
        "source":                   path,
        "rows":                     total,
        "elapsed_seconds":          round(total_elapsed, 2),
        "throughput_rows_per_second": round(final_tp, 0),
    }


def run_benchmark_queries(client: Client) -> list[dict[str, Any]]:
    """
    Execute the benchmark query suite and report latencies.
    These queries are duplicated in src/analytics/queries/benchmark_queries.sql
    for manual execution in ClickHouse Play / DBeaver.
    """
    queries = [
        {
            "name": "01_count_all_forecasts",
            "sql":  "SELECT count() FROM cartaq.forecast_log",
        },
        {
            "name": "02_top20_hex_by_avg_aqi",
            "sql":  """
                SELECT h3_index, round(avg(predicted_aqi), 1) AS avg_aqi, count() AS n
                FROM cartaq.forecast_log
                GROUP BY h3_index
                ORDER BY avg_aqi DESC
                LIMIT 20
            """,
        },
        {
            "name": "03_daily_peak_aqi_last_90_days",
            "sql":  """
                SELECT toDate(future_timestamp) AS day,
                       max(predicted_aqi)       AS peak_aqi
                FROM cartaq.forecast_log
                WHERE future_timestamp >= (now() - INTERVAL 90 DAY)
                GROUP BY day
                ORDER BY day DESC
            """,
        },
        {
            "name": "04_attribution_by_source_type",
            "sql":  """
                SELECT source_type,
                       round(avg(ate), 2)                AS mean_ate,
                       round(quantile(0.95)(ate), 2)     AS p95_ate,
                       countIf(is_source_active = 1)     AS active_events,
                       count()                           AS total_events
                FROM cartaq.attribution_log
                GROUP BY source_type
                ORDER BY mean_ate DESC
            """,
        },
        {
            "name": "05_hex_spike_factory_top20",
            "sql":  """
                SELECT h3_index, count() AS spike_count
                FROM cartaq.attribution_log
                WHERE source_type = 'factory' AND ate > 50
                GROUP BY h3_index
                ORDER BY spike_count DESC
                LIMIT 20
            """,
        },
        {
            "name": "06_hourly_aqi_from_mv",
            "sql":  """
                SELECT hour_bucket,
                       round(avg(avg_aqi), 1)  AS mean_avg_aqi,
                       round(max(max_aqi), 1)  AS overall_max
                FROM cartaq.hourly_aqi
                GROUP BY hour_bucket
                ORDER BY hour_bucket DESC
                LIMIT 48
            """,
        },
        {
            "name": "07_model_comparison",
            "sql":  """
                SELECT model_version,
                       round(avg(predicted_aqi), 2)                         AS mean_aqi,
                       round(sqrt(avg(pow(predicted_aqi - 100, 2))), 2)     AS pseudo_rmse
                FROM cartaq.forecast_log
                GROUP BY model_version
                ORDER BY pseudo_rmse ASC
            """,
        },
    ]

    results = []
    print("\n--- Benchmark Query Suite ---")
    for q in queries:
        t0 = time.perf_counter()
        rows = client.execute(q["sql"])
        latency_ms = (time.perf_counter() - t0) * 1000
        print(f"  {q['name']:45s}  {latency_ms:7.1f} ms  ({len(rows)} result rows)")
        results.append({
            "query":       q["name"],
            "latency_ms":  round(latency_ms, 1),
            "result_rows": len(rows),
        })

    return results


def main(table_filter: str = "all") -> None:
    print("=" * 60)
    print("  Cartaq Role 3 - ClickHouse Ingestion Pipeline")
    print("=" * 60)

    client = get_client()
    ingest_metrics: list[dict] = []

    for plan in INGEST_PLAN:
        if table_filter not in ("all", plan["name"]):
            continue

        print(f"\n[{plan['name']}]")
        for src in plan["sources"]:
            if not os.path.exists(src):
                print(f"  SKIP: {src} not found (run generate_fake_data.py first)")
                continue
            m = ingest_file(client, src, plan["table"])
            ingest_metrics.append(m)

    # Benchmark queries
    benchmark = run_benchmark_queries(client)

    # Persist metrics
    output = {
        "ingestion_metrics":         ingest_metrics,
        "benchmark_query_latencies": benchmark,
    }
    from pathlib import Path
    metrics_path = Path(__file__).parent.parent.parent / "metrics_role3.json"
    with open(metrics_path, "w") as f:
        json.dump(output, f, indent=2)

    print(f"\n✓  Metrics saved -> {metrics_path}")
    print("   Next step: open Superset at http://localhost:8088 and configure the ClickHouse datasource.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Cartaq ClickHouse ingestion pipeline")
    parser.add_argument(
        "--table",
        choices=["forecast", "attribution", "all"],
        default="all",
        help="Which table to ingest (default: all)",
    )
    args = parser.parse_args()
    main(table_filter=args.table)
